### ISSUE TITLE
Action doesnt work if PR is in open state

### ISSUE THREAD

**Issue by vcharan17** [zwaldowski/match-label-action#34]
The action does not work if PR is in open state. Doesn't work on PR sync events either. It only works when I merge the PR (i.e,. PR closed state). **_Note: I've checked that the correct label is in my PR already by the time this action runs._** 
I use this action to get bump rule label from my PR and do a dry-run for next semantic tag as per the bump label. But, I am only able to do this when I close the PR, which renders my usecase of dry-run moot.

Am I using the action wrong?

![image](https://user-images.githubusercontent.com/118737392/215352080-8230c254-4330-49ad-9b5b-d2d27b730ee0.png)

**Comment by zwaldowski** [comment]
This action is known to work on other `on.pull_request` types like `opened`, `synchronize`, `reopened`, `labeled`, `unlabeled`, etc. Unfortunately, I can't debug a screenshot.

**Comment by vcharan17** [comment]
Ok. I have pasted a snippet from my workflow below:
```
pr-labeler:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: TimonVS/pr-labeler-action@v4.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/config/pr-labeler.yml

get_bump_version:
    needs: [ pr-labeler ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == false ))
    permissions: write-all
    steps:
      - name: Checkout application GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

     - name: Check and return bump label from PR
        id: get_version_label
        uses: zwaldowski/match-label-action@v4
        with:
          allowed: major, minor, patch

```
In that, I have two jobs in my workflow - one for labelling the PR which runs when PR is opened and another for getting version label (major/minor/patch) from the PR (executes in each workflow run from PR opening until PR is merged). 
My understanding was that this action should work as-is. But unfortunately, it fails for me with the error shown in the snapshot.
